const styles = {
  container: {
    fontFamily: "Arial, sans-serif",
    height: "80vh",
    width: "100%",
    margin: "auto",
    backgroundColor: "#E0F2F1",
    color: "black",
    position: "relative",
    overflowX: "hidden",
    scrollbarWidth: "none", // Hides scrollbar in Firefox
    msOverflowStyle: "none", // Hides scrollbar in IE/Edge
    display: "flex",
    flexDirection: "column",
    flex: "1"
  },
  header: {
    backgroundColor: "#21C3BC",
    padding: "10px 15px 30px 15px",
    color: "Black",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 0,
    position: "relative",
    gap: "10px",
    width: "100%",
  },
  greeting: {
    textAlign: "left",
    marginBottom: "0",
    padding: "0",
  },
  title: {
    margin: "0",
    fontSize: "22px",
    display: "flex",
  },
  subtitle: {
    margin: "5px 0 0",
    fontSize: "14px",
  },
  icons: {
    display: "flex",
    gap: "15px",
    alignSelf: "flex-end",
    marginRight: "30px",
  },
  icon: {
    width: "32px", 
    height: "32px", 
    cursor: "pointer",
    backgroundColor: "white",
    borderRadius: "40px"
  },
  searchContainer: {
    marginRight: "30px",
    display: "flex",
    alignItems: "center",
    backgroundColor: "#E0F2F1",
    borderRadius: "20px",
    padding: "10px 15px",
    maxWidth: "300px",
    marginTop: "15px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    width: "100%",
    transition: "all 0.3s ease", 
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    fontSize: "16px",
    fontFamily: "Arial, sans-serif",
    color: "black",
    transition: "width 0.3s ease", 
  },
  searchIcon: {
    fontSize: "20px",
    color: "#009688",
    cursor: "pointer",
  },
  whiteLayer: {
    backgroundColor: "white",
    borderTopLeftRadius: "30px",
    borderTopRightRadius: "30px",
    marginTop: "-20px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    zIndex: 1,
    position: "relative",
    width: "100%",
    // minHeight: "300px",
    // maxHeight: "calc(100vh - 120px)",
    boxSizing: "border-box",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  buttonsContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "20px 20px",
  },
  button: {
    backgroundColor: "#3CB3D0",
    padding: "15px 30px",
    borderRadius: "10px",
    fontSize: "16px",
    fontWeight: "bold",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "10px",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  studentList: {
    backgroundColor: "white",
    borderRadius: "10px",
    boxShadow: "0px 4px 6px rgba(0,0,0,0.1)",
    marginTop: "20px",
    maxHeight: "470px", 
    overflowY: "auto", 
    padding: "10px",
    scrollbarWidth: "thin", 
    height: "335px"
  },
  studentItem: {
    padding: "15px",
    display: "flex",
    justifyContent: "space-between",
    fontSize: "16px",
    cursor: "pointer",
  },
  studentDetails: {
    padding: "10px",
    backgroundColor: "#E0F2F1",
    fontSize: "14px",
    borderBottomLeftRadius: "10px",
    borderBottomRightRadius: "10px",
  },
  arrow: {
    width: "20px", 
    height: "20px", 
  },
  navButton: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "10px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50%",
    transition: "background-color 0.3s",
  },
  bottomNav: {
    position: "fixed",
    bottom: "0",
    left: "0",
    width: "100%",
    backgroundColor: "#12736F",
    display: "flex",
    justifyContent: "space-around",
    padding: "15px 0",
    borderTopLeftRadius: "20px",
    borderTopRightRadius: "20px",
    boxShadow: "0 -2px 6px rgba(0,0,0,0.1)",
    zIndex: 10,
  },
  navItem: {
    textAlign: "center",
    flex: 1,
  },
  navIcon: {
    fontSize: "24px",
    marginBottom: "5px",
  },
  navLabel: {
    fontSize: "12px",
    color: "#555",
  },
  activeNavItem: {
    color: "#009688",
    fontWeight: "bold",
  },
};

export default styles;
